options {
  directory "/var/cache/bind";
  listen-on port 53 { any; };
  listen-on-v6 port 53 { any; };
  recursion no;
  allow-query { any; };
  dnssec-validation no;
};

key "darkarts-tsig" {
  algorithm hmac-sha256;
  secret "22jBF/BOePhdr9ocfm1Nb9VSUQFp1jn5KbxdO4bpneE=";
};

zone "darkarts.lab" IN {
  type master;
  file "/etc/bind/db.darkarts.lab";
  allow-update { key darkarts-tsig; };
};
